version: "3"
services:

  mongo:
    image: mongo:latest
    restart: always
    hostname: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: mongopw
    volumes:
      - ./mongo:/data/db 

  mongo-express:
    image: mongo-express:latest
    hostname: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongopw
      ME_CONFIG_MONGODB_URL: mongodb://admin:mongopw@mongo:27017/
    depends_on: 
      - mongo

  drill:
    image: apache/drill:1.19.0
    hostname: drill
    command: /bin/bash
    tty: true
    ports:
    - "8047:8047"
    depends_on:
    - mongo
    - minio
    links:
    - mongo
    - minio

  jupyter:
    image: ist769/jupyter_pyspark:20210924b 
    environment:
      - GRANT_SUDO=yes
      - JUPYTER_ENABLE_LAB=yes       
    ports:
      - "8888:8888"
    volumes: 
      - ./work:/home/jovyan/work
    depends_on:
      - mongo
    links:
      - mongo

  minio:
    image: minio/minio:latest
    hostname: minio
    volumes: 
      -  ./data:/data 
    command: server /data --console-address ":9001"
    ports:
    - "9000:9000"
    - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: SU2orange!
